workspace(name = "bzlmodrio-opencv-gentool")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Python, for gentool
http_archive(
    name = "rules_python",
    sha256 = "f609f341d6e9090b981b3f45324d05a819fd7a5a56434f849c761971ce2c47da",
    strip_prefix = "rules_python-1.7.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.7.0/rules_python-1.7.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

local_repository(
    name = "bzlmodrio-gentool",
    path = "../../../../gentool",
)

python_register_toolchains(
    name = "python_3_10",
    ignore_root_user_error = True,
    python_version = "3.10",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "bzlmodrio-gentool-pip",
    python_interpreter_target = "@python_3_10_host//:python",
    requirements_lock = "@bzlmodrio-gentool//:requirements_lock.txt",
)

load("@bzlmodrio-gentool-pip//:requirements.bzl", "install_deps")

install_deps()
